Test update
Signed-off-by: Jason T. Greene <jason.greene@redhat.com>

diff --git a/.cirrus.yml b/.cirrus.yml
--- a/.cirrus.yml
+++ b/.cirrus.yml
@@ -4,18 +4,127 @@ env:
   CIRRUS_SHELL: bash
   IMAGE_SUFFIX: "c20240227t125812z-f39f38d13"
   FEDORA_AARCH64_AMI: "fedora-podman-aws-arm64-${IMAGE_SUFFIX}"
+  FEDORA_AMI: "fedora-aws-${IMAGE_SUFFIX}"
+
 
 aws_credentials: ENCRYPTED[1625a7241b4d8c8b56fab6419ba3cd6969f44c854568d12166cb9a32688784c5cc4570d7e3d9c4f03d143e275a50b819]
 
 build_task:
   alias: 'build'
   only_if: $CIRRUS_BRANCH == 'main' && $CIRRUS_PR == "" && $CIRRUS_TAG == ""
-  #execution_lock: podman-wsl-fedora-arm-serial
+  # execution_lock: podman-wsl-fedora-arm-serial
   auto_cancellation: true
-  ec2_instance: &standard_build_ec2_aarch64
-    image: ${FEDORA_AARCH64_AMI}
+  env:
+    matrix:
+      - BUILD_ARCH: "arm64"
+        USE_AMI: $FEDORA_AARCH64_AMI
+      - BUILD_ARCH: "amd64"
+        USE_AMI: $FEDORA_AMI
+    LAST_IMAGE_FILE: latest-$BUILD_ARCH
+  ec2_instance:
+    image: $USE_AMI
     type: "t4g.xlarge"
     region: us-east-1
-    architecture: arm64
-  main_script: |
-    echo "Hello World"
+    architecture: $BUILD_ARCH
+  setup_script: |
+    dnf install 'dnf-command(config-manager)'
+    dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
+    dnf -y install gh git podman golang
+  get_script: |
+    set +o verbose
+    date >> changes
+    podman image pull docker.io/library/fedora:$IMAGE_TAG
+    imageDigest=`podman image inspect docker.io/library/fedora:$IMAGE_TAG --format {{.Digest}}`
+    echo $imageDigest > "$LAST_IMAGE_FILE"
+    echo "Fetching $GITHUB_SERVER_URL/$CIRRUS_REPO_FULL_NAME/releases/latest/download/$LAST_IMAGE_FILE"
+    lastImage=`curl --retry 5 --retry-delay 8 --retry-all-errors -L "$GITHUB_SERVER_URL/$CIRRUS_REPO_FULL_NAME/releases/latest/download/$LAST_IMAGE_FILE`
+    echo "Digest: $imageDigest"
+    echo "Last: $lastImage"
+    if [ "$lastImage" != "$imageDigest" ]; then
+      echo "Image needs update"
+      echo -e "\nImage update:\n $imageDigest\n" >> changes
+      echo "IMAGE_CHANGED=1" >> $CIRRUS_ENV
+    fi
+  reuse_script: |
+    set +o verbose
+    if [ "$IMAGE_CHANGED" == "1" ]; then
+      echo "Skipped"
+      exit
+    fi
+    echo "Reusing cached image"
+    curl --retry 5 --retry-delay 8 --retry-all-errors -L $GITHUB_SERVER_URL/$CIRRUS_REPO_FULL_NAME/releases/latest/download/rootfs.tar.xz --output rootfs.tar.xz
+    echo "Extracting rootfs.."
+    unxz rootfs.tar.xz
+    podman import rootfs.tar fedora-update
+    podman create --name fedora-update fedora-update sleep 7200
+  clean_script: |
+    set +o verbose
+    if [ "$IMAGE_CHANGED" != "1" ]; then
+      echo "Skipped"
+      exit
+    fi
+    echo "Using clean image"
+    podman create --name fedora-update docker.io/library/fedora:$IMAGE_TAG sleep 7200
+  update_script: |
+    set +o verbos
+    podman start fedora-update
+    podman exec fedora-update sh -c 'rpm -qa --qf "%-30{name} %{version}-%{release}\n" | sort' > pre-update
+    podman exec -it fedora-update sh -c 'dnf update -y && dnf -y install podman podman-docker procps-ng openssh-server net-tools iproute dhcp-client crun-wasm wasmedge-rt && dnf clean all && rm -rf /var/cache/yum'
+    podman exec fedora-update sh -c 'rpm -qa --qf "%-30{name} %{version}-%{release}\n" | sort' > post-update
+
+    diff -u pre-update post-update > delta || delta=1
+    if [ ! -z "$delta" ]; then
+      echo "Package changes!"
+      echo -e "\nInstalled packages:\n\`\`\`" >> changes
+      grep '^+' delta | grep -v '+++' | sed 's/^\+//g' >> changes
+      echo "\`\`\`" >> changes
+      echo "PACKAGE_CHANGED=1" >> $CIRRUS_ENV
+    fi
+  archive_script: |
+    set +o verbose
+    if [ "$IMAGE_CHANGED" != "1" ] && [ "$PACKAGE_CHANGED" != "1" ]; then
+      echo "Skipping archive, no updates required"
+      exit
+    fi
+    echo "Creating rootfs.tar from container..."
+    podman export --output rootfs.tar fedora-update
+    # GNu tar has a corruption bugs with --delete, so use bsdtar to filter instead
+    echo "Filtering rootfs.tar using container..."
+    podman run -v .:/mnt --security-opt label=disable fedora sh -c 'dnf -y install bsdtar && bsdtar -cf /mnt/new.tar --exclude etc/resolv.conf @/mnt/rootfs.tar'
+    mv new.tar rootfs.tar
+    mkdir -p etc; touch etc/resolv.conf
+    tar rf "rootfs-$BUILD_ARCH.tar" --mode=644 --group=root --owner=root etc/resolv.conf
+    echo "Compressing rootfs.tar.."
+    xz --verbose "rootfs-$BUILD_ARCH.tar"
+    echo "Done"
+    ls -l rootfs*.tar.xz
+    mkdir upload-$BUILD_ARCH
+    mv rootfs*.tar.xz "$LAST_IMAGE_FILE" "upload-$BUILD_ARCH"
+  arm_cache:
+    only_if: $IMAGE_CHANGED == "1" || $PACKAGE_CHANGED == "1"
+    folder: ./upload-$BUILD_ARCH
+    type: application/octet-stream
+
+
+
+
+ # release_script: |
+ #   set +o verbose
+ #   if [ "$IMAGE_CHANGED" != "1" ] && [ "$PACKAGE_CHANGED" != "1" ]; then
+ #     echo "Skipping release, no updates required"
+ #     exit
+ #   fi
+ #   git fetch --tags
+ #  set +o pipefail
+ #  NEXT_RELEASE=`git tag --list | grep v${IMAGE_TAG} | cut -f3 -d '.' | sort -n | tail -1`
+ #  re='^[0-9]+$'
+ #  if ! [[ $NEXT_RELEASE =~ $re ]] ; then
+ #    NEXT_RELEASE=0
+ #  fi
+ #  NEXT_RELEASE="v${IMAGE_TAG}.0.$((NEXT_RELEASE+1))"
+ #  echo $NEXT_RELEASE > version
+ #  echo "Releasing $NEXT_RELEASE"
+ #  set -o verbose
+ #  gh release create $NEXT_RELEASE -t $NEXT_RELEASE -d -F changes
+ #  gh release upload $NEXT_RELEASE lastimage rootfs.tar.xz shasums version
+ #  gh release edit $NEXT_RELEASE --draft=false
